apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: crossplane-system
type: Opaque
data:
  aws_access_key_id: REDACTED_ACCESS_KEY_ID
  aws_secret_access_key: REDACTED_SECRET_ACCESS_KEY
  aws_access_token: REDACTED_ACCESS_TOKEN
