apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: crossplane
  namespace: kube-system
spec:
  chart: crossplane
  repo: https://charts.crossplane.io/stable
  targetNamespace: crossplane-system
  set:
    args: "{--enable-composition-functions}"
    replicas: "1"
    metrics.enabled: "true"