apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rfrozza/crossplane-gitops-lab.git
    targetRevision: master
    path: applications/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true