apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-platform-apis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rfrozza/crossplane-gitops-lab.git
    targetRevision: master
    path: infrastructure/crossplane/platform-apis
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m